# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: recommendation.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'recommendation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14recommendation.proto\x12\x0erecommendation\"K\n\x15RecommendationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\x12\x12\n\ncategories\x18\x03 \x03(\t\"d\n\x16RecommendationResponse\x12)\n\x08products\x18\x01 \x03(\x0b\x32\x17.recommendation.Product\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"\xc7\x01\n\x0fUserPreferences\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x1b\n\x13\x66\x61vorite_categories\x18\x02 \x03(\t\x12N\n\x10\x63\x61tegory_weights\x18\x03 \x03(\x0b\x32\x34.recommendation.UserPreferences.CategoryWeightsEntry\x1a\x36\n\x14\x43\x61tegoryWeightsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"2\n\x0eUpdateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"2\n\x0fTrendingRequest\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\"F\n\x10TrendingResponse\x12\x32\n\x11trending_products\x18\x01 \x03(\x0b\x32\x17.recommendation.Product\"\xae\x01\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\r\n\x05score\x18\x04 \x01(\x02\x12\x37\n\x08metadata\x18\x05 \x03(\x0b\x32%.recommendation.Product.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\xb6\x02\n\x15RecommendationService\x12\x65\n\x12GetRecommendations\x12%.recommendation.RecommendationRequest\x1a&.recommendation.RecommendationResponse\"\x00\x12Z\n\x15UpdateUserPreferences\x12\x1f.recommendation.UserPreferences\x1a\x1e.recommendation.UpdateResponse\"\x00\x12Z\n\x13GetTrendingProducts\x12\x1f.recommendation.TrendingRequest\x1a .recommendation.TrendingResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recommendation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERPREFERENCES_CATEGORYWEIGHTSENTRY']._loaded_options = None
  _globals['_USERPREFERENCES_CATEGORYWEIGHTSENTRY']._serialized_options = b'8\001'
  _globals['_PRODUCT_METADATAENTRY']._loaded_options = None
  _globals['_PRODUCT_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_RECOMMENDATIONREQUEST']._serialized_start=40
  _globals['_RECOMMENDATIONREQUEST']._serialized_end=115
  _globals['_RECOMMENDATIONRESPONSE']._serialized_start=117
  _globals['_RECOMMENDATIONRESPONSE']._serialized_end=217
  _globals['_USERPREFERENCES']._serialized_start=220
  _globals['_USERPREFERENCES']._serialized_end=419
  _globals['_USERPREFERENCES_CATEGORYWEIGHTSENTRY']._serialized_start=365
  _globals['_USERPREFERENCES_CATEGORYWEIGHTSENTRY']._serialized_end=419
  _globals['_UPDATERESPONSE']._serialized_start=421
  _globals['_UPDATERESPONSE']._serialized_end=471
  _globals['_TRENDINGREQUEST']._serialized_start=473
  _globals['_TRENDINGREQUEST']._serialized_end=523
  _globals['_TRENDINGRESPONSE']._serialized_start=525
  _globals['_TRENDINGRESPONSE']._serialized_end=595
  _globals['_PRODUCT']._serialized_start=598
  _globals['_PRODUCT']._serialized_end=772
  _globals['_PRODUCT_METADATAENTRY']._serialized_start=725
  _globals['_PRODUCT_METADATAENTRY']._serialized_end=772
  _globals['_RECOMMENDATIONSERVICE']._serialized_start=775
  _globals['_RECOMMENDATIONSERVICE']._serialized_end=1085
# @@protoc_insertion_point(module_scope)
