# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.protos import recommendation_pb2 as recommendation__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in recommendation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RecommendationServiceStub(object):
    """Service de recommandation
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRecommendations = channel.unary_unary(
                '/recommendation.RecommendationService/GetRecommendations',
                request_serializer=recommendation__pb2.RecommendationRequest.SerializeToString,
                response_deserializer=recommendation__pb2.RecommendationResponse.FromString,
                _registered_method=True)
        self.UpdateUserPreferences = channel.unary_unary(
                '/recommendation.RecommendationService/UpdateUserPreferences',
                request_serializer=recommendation__pb2.UserPreferences.SerializeToString,
                response_deserializer=recommendation__pb2.UpdateResponse.FromString,
                _registered_method=True)
        self.GetTrendingProducts = channel.unary_unary(
                '/recommendation.RecommendationService/GetTrendingProducts',
                request_serializer=recommendation__pb2.TrendingRequest.SerializeToString,
                response_deserializer=recommendation__pb2.TrendingResponse.FromString,
                _registered_method=True)


class RecommendationServiceServicer(object):
    """Service de recommandation
    """

    def GetRecommendations(self, request, context):
        """Obtenir des recommandations pour un utilisateur
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUserPreferences(self, request, context):
        """Mettre à jour les préférences utilisateur
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrendingProducts(self, request, context):
        """Obtenir les produits tendance
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecommendationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRecommendations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecommendations,
                    request_deserializer=recommendation__pb2.RecommendationRequest.FromString,
                    response_serializer=recommendation__pb2.RecommendationResponse.SerializeToString,
            ),
            'UpdateUserPreferences': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUserPreferences,
                    request_deserializer=recommendation__pb2.UserPreferences.FromString,
                    response_serializer=recommendation__pb2.UpdateResponse.SerializeToString,
            ),
            'GetTrendingProducts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrendingProducts,
                    request_deserializer=recommendation__pb2.TrendingRequest.FromString,
                    response_serializer=recommendation__pb2.TrendingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'recommendation.RecommendationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('recommendation.RecommendationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RecommendationService(object):
    """Service de recommandation
    """

    @staticmethod
    def GetRecommendations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommendation.RecommendationService/GetRecommendations',
            recommendation__pb2.RecommendationRequest.SerializeToString,
            recommendation__pb2.RecommendationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUserPreferences(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommendation.RecommendationService/UpdateUserPreferences',
            recommendation__pb2.UserPreferences.SerializeToString,
            recommendation__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTrendingProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommendation.RecommendationService/GetTrendingProducts',
            recommendation__pb2.TrendingRequest.SerializeToString,
            recommendation__pb2.TrendingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
